### ISSUE TITLE
FNC1 Bug in FindStartorCodeCharacter

### ISSUE THREAD

**Issue by LordPinhead** [bbarnhill/Code128_CPP#1]
Hi Brad,

for my curiosity, i looked at your Code128_CPP Library, in the C128.h
at line 425 i found the same bug as in the C# version:

if (s.size() > 1 && (isdigit(s[0]) || &s[0] == FNC1) && (isdigit(s[1]) || &s[0] == FNC1))

should be:
if (s.size() > 1 && (isdigit(s[0]) || &s[0] == FNC1) && (isdigit(s[1]) || &s[1] == FNC1))

Just close it when you changed it, the C# Version worked to.

Regards

**Comment by barnhill** [comment]
you are correct ... I generated this library from a consulting project that I was ultimately not paid a dime for (Im still bitter about that if you cant tell).  Since it was a port form the C# version it has the same bug.  Good eye on checking this one too!!! :)

**Comment by barnhill** [comment]
Fixed by https://github.com/barnhill/Code128_CPP/commit/41407902af7e6ce7cf0360e61bced279053757ec

**Comment by barnhill** [comment]
@LordPinhead thanks for you dedication and help on this.  You rock.
