### ISSUE TITLE
Arduino Compatible

### ISSUE THREAD

**Issue by maksumon** [bbarnhill/Code128_CPP#2]
Hi, Is this library compatible with Arduino?

**Comment by barnhill** [comment]
Never tried it but it was compatible with ansi c++ 98 compilers

**Comment by maksumon** [comment]
Okay, I'll give it a try soon and will let you know.

**Comment by barnhill** [comment]
Yes please do.  Enjoy!!!

**Comment by barnhill** [comment]
Closing since it's not currently an issue but do report back here if you find a bug.
